# .github/workflows/pages.yml
name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Enable Corepack (Yarn)
        run: corepack enable

      - name: Install deps
        run: yarn install --frozen-lockfile

      # Optional: keep or remove if you don't want lint to block deploys
      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      # For client-side routing (Vite SPA): make GitHub Pages serve index on 404
      - name: SPA fallback
        run: node -e "require('fs').copyFileSync('dist/index.html','dist/404.html')"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
